version: "3"

services:
  torproxy:
    image: ghcr.io/cyberworm-uk/tor-client:latest
    restart: unless-stopped
    volumes:
      - type: volume
        source: var-lib-tor
        target: /var/lib/tor
    networks:
      pihole_net:
        ipv4_address: 10.69.0.4

  dohproxy:
    image: ghcr.io/cyberworm-uk/dnscrypt-proxy:latest
    restart: unless-stopped
    volumes:
      - "./dnscrypt-proxy.toml:/etc/dnscrypt-proxy/dnscrypt-proxy.toml"
    networks:
      pihole_net:
        ipv4_address: 10.69.0.2
    depends_on:
      - torproxy

  pihole:
    image: docker.io/pihole/pihole
    restart: unless-stopped
    volumes:
      - type: volume
        source: etc-dnsmasqd
        target: /etc/dnsmasq.d/
      - type: volume
        source: etc-pihole
        target: /etc/pihole/
#    ports:
#      - "YOUR_LAN_IP_HERE:80:80/tcp"
#      - "YOUR_LAN_IP_HERE:53:53/tcp"
#      - "YOUR_LAN_IP_HERE:53:53/udp"
    environment:
      - FTLCONF_dns_blockESNI=false
      - FTLCONF_dns_upstreams=10.69.0.2#5054
      - FTLCONF_dns_listeningMode=all
      - FTLCONF_webserver_port=80o
      - FTLCONF_REPLY_ADDR4=10.69.0.3
      - TZ=Europe/London
    networks:
      pihole_net:
        ipv4_address: 10.69.0.3
    dns:
      - 127.0.0.1
    depends_on:
      - dohproxy

networks:
  pihole_net:
    ipam:
      config:
      - subnet: 10.69.0.0/29

volumes:
  etc-dnsmasqd:
  etc-pihole:
  var-lib-tor: