name: Docker Image (dohproxy)

on:
  schedule:
    - cron: '30 00 * * 5'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  DOCKERHUB_USERNAME: cyberwormuk

jobs:
  ghcr_publish:
    permissions:
      id-token: write
      packages: write
      contents: read
      attestations: write
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log-in to registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Log-in to registry
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER }}

      - name: Build and push DOH Proxy
        uses: docker/build-push-action@v6
        id: pushproxy
        env:
          SOURCE_DATE_EPOCH: 0
        with:
          context: dnscrypt-proxy/
          platforms: linux/amd64,linux/arm64/v8,linux/arm/v7
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ github.actor }}/dohproxy:latest
            ${{ env.DOCKERHUB_USERNAME }}/dohproxy:latest
            ${{ env.REGISTRY }}/${{ github.actor }}/doh-proxy:latest
            ${{ env.DOCKERHUB_USERNAME }}/doh-proxy:latest

      - name: Attest
        uses: actions/attest-build-provenance@v1
        id: attestproxy
        with:
          subject-name: ${{ env.REGISTRY }}/${{ github.actor }}/doh-proxy
          subject-digest: ${{ steps.pushproxy.outputs.digest }}
          push-to-registry: true

      - name: Build and push DOH Front
        uses: docker/build-push-action@v6
        id: pushfront
        env:
          SOURCE_DATE_EPOCH: 0
        with:
          context: doh-server/
          platforms: linux/amd64,linux/arm64/v8
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ github.actor }}/doh-front:latest
            ${{ env.DOCKERHUB_USERNAME }}/doh-front:latest

      - name: Attest
        uses: actions/attest-build-provenance@v1
        id: attestfront
        with:
          subject-name: ${{ env.REGISTRY }}/${{ github.actor }}/doh-front
          subject-digest: ${{ steps.pushfront.outputs.digest }}
          push-to-registry: true